# Set the base image
FROM node:20

# Set working directory
WORKDIR /var/www

# Copy `package.json` and `package-lock.json`
COPY ./src_clients/package*.json ./

# Install project dependencies
RUN npm install

# Copy project files into the docker image
#COPY ./src_clients .

# Expose the port Vite runs on
EXPOSE 8000

# Start the Vite server
CMD ["npm", "run", "dev"]